# Generated by Django 3.0.4 on 2020-03-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
